#!/usr/bin/env python3
"""Serialize unchanged, independently referenced inputs for limit regressions."""
import argparse
import importlib.util
from pathlib import Path
import subprocess
import sys

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'decode_limits_fixtures_test.mbt'
INPUTS = {
    'raw': 'av1-palette/color_64x64_10bit_3colors.obu',
    'hidden': 'av1-obu-assembly/hidden_inter_show_existing.obu',
    'grid': 'avif-grid/alpha_grid_grid_12bit.avif',
    'animation': 'avif-premultiplied-alpha/animation_matrix6_12bit.avif',
    'superres': 'av1-superres/stock_color_10bit_d16_97x65_1tile.obu',
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    spec = importlib.util.spec_from_file_location('limits_embed', Path(__file__).with_name('generate-native-api-tests.py'))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    lines = ['/// Generated by scripts/generate-limits-fixtures.py from saved inputs.\n'
             '/// Independent references/provenance remain in each fixture directory.\n']
    for name, path in INPUTS.items():
        lines.append(f'///|\n// tests/fixtures/{path}\nfn limits_{name}() -> Array[Byte] {{\n'
                     + module.input_expr(ROOT / 'tests/fixtures' / path) + '\n}')
    text = subprocess.run(['moonfmt', '-'], input='\n'.join(lines), text=True,
                          encoding='utf-8', capture_output=True, check=True).stdout
    if args.check:
        if OUTPUT.read_text(encoding='utf-8') != text:
            raise SystemExit('Limit test inputs differ from saved fixtures')
        print('Limit inputs checked: 5 unchanged independent fixtures')
    else:
        OUTPUT.write_text(text, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
