#!/usr/bin/env python3
"""Independent HD and reordered video references with frame-at-a-time embedding.

Existing corpora are never rewritten. --check is read-only; --redecode also
compares saved pixels with dav1d and the still image with libavif.
"""

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
import importlib.util

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('stream_large', Path(__file__).with_name('generate-large-reference.py'))
large = importlib.util.module_from_spec(spec)
spec.loader.exec_module(large)
OUT = ROOT / 'tests/fixtures/av1-stream'
EMBED = ROOT / 'benchmarks/stream/fixtures.mbt'
SPECS = [
    dict(name='still_12bit_1280x720', width=1280, height=720, depth=12, frames=1, lag=0),
    dict(name='reorder_10bit_320x180', width=320, height=180, depth=10, frames=32, lag=16),
]


def evidence(case, headers, units):
    displayed = sum(h.get('show_frame', 0) + h.get('show_existing_frame', 0) for h in headers)
    # A reduced still header infers its show_frame and frame_type.
    if case['frames'] == 1:
        displayed = 1
    if displayed != case['frames'] or len(units) != case['frames']:
        raise ValueError(f"Unexpected presentations/temporal units for {case['name']}")
    result = dict(temporal_units=len(units), presentations=displayed,
                  hidden_frames=sum(h.get('show_frame') == 0 and not h.get('show_existing_frame') for h in headers),
                  show_existing_frames=sum(h.get('show_existing_frame', 0) for h in headers),
                  inter_frames=sum(h.get('frame_type') == 1 for h in headers))
    if case['lag'] and not (result['hidden_frames'] and result['show_existing_frames'] and result['inter_frames']):
        raise ValueError('Encoder did not exercise reordered inter pictures')
    return result


def embedded(cases):
    helpers = large.embed.HELPERS[large.embed.HELPERS.index('///|'):]
    helpers = helpers[:helpers.index('///|\nfn native_test_frame')]
    lines = ['/// Generated by scripts/generate-stream-reference.py.\n'
             '/// Independent dav1d samples, expanded only for the requested frame.\n', helpers]
    for index, case in enumerate(cases):
        name = case['name']
        values = large.embed.samples(OUT / f'{name}.reference.yuv', case['depth'])
        size = case['width'] * case['height'] * 3 // 2
        for frame in range(case['frames']):
            parts = []
            for chunk, start in enumerate(range(frame * size, (frame + 1) * size, 32768)):
                end = min(start + 32768, (frame + 1) * size)
                fun = f'stream_ref_{index}_{frame}_{chunk}'
                lines.append(f'///|\nfn {fun}() -> Array[Int] {{\n'
                             + large.embed.reference_expr(values[start:end]) + '\n}')
                parts.append(f'for value in {fun}() {{ result.push(value) }}')
            lines.append(f'///|\nfn stream_frame_{index}_{frame}() -> Array[Int] {{\n'
                         + 'let result = []\n' + '\n'.join(parts) + '\nresult\n}')
        arms = '\n'.join(f'{frame} => stream_frame_{index}_{frame}()' for frame in range(case['frames']))
        lines.append(f'///|\nfn stream_reference_{index}(frame : Int) -> Array[Int] {{\n'
                     + f'match frame {{\n{arms}\n_ => abort("Invalid reference frame")\n}}\n}}')
        units = large.temporal_units((OUT / f'{name}.obu').read_bytes())
        for unit, data in enumerate(units):
            lines.append(f'///|\nfn stream_unit_{index}_{unit}() -> Array[Byte] {{\n'
                         + 'native_test_bytes(' + large.embed.hex_rows(data) + ')\n}')
        metadata = case['sequence_metadata']
        avif = 'Some(' + large.embed.input_expr(OUT / f'{name}.avif') + ')' if case['frames'] == 1 else 'None'
        calls = ', '.join(f'stream_unit_{index}_{u}()' for u in range(len(units)))
        lines.append(f'''///|
fn stream_fixture_{index}() -> StreamFixture {{
  {{ name: "{name}", width: {case['width']}, height: {case['height']},
    depth: {case['depth']}, frames: {case['frames']}, units: [{calls}],
    primaries: {metadata['color_primaries']}, transfer: {metadata['transfer_characteristics']},
    matrix: {metadata['matrix_coefficients']}, full: {str(bool(metadata['color_range'])).lower()},
    avif: {avif}, reference: stream_reference_{index} }}
}}''')
    return subprocess.run(['moonfmt', '-'], input='\n'.join(lines), capture_output=True,
                          text=True, encoding='utf-8', check=True).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--embed-only', action='store_true')
    parser.add_argument('--redecode', action='store_true')
    parser.add_argument('--ffmpeg', default='ffmpeg')
    parser.add_argument('--dav1d', default='dav1d')
    parser.add_argument('--libavif', help='libavif 0.11.1 library; required for generation')
    args = parser.parse_args()
    if args.check and args.embed_only:
        parser.error('--check and --embed-only are mutually exclusive')
    module = lib = dll_directory = None
    if args.libavif:
        if hasattr(os, 'add_dll_directory'):
            dll_directory = os.add_dll_directory(str(Path(args.libavif).resolve().parent))
        module = large.load('stream_libavif', 'generate-avif-premultiplied-alpha-reference.py')
        lib, lib_version = module.library(args.libavif)
    if not args.check and not args.embed_only:
        if lib is None:
            parser.error('generation requires --libavif')
        if (OUT / 'manifest.json').exists():
            parser.error('saved corpus already exists; use --check or --embed-only')
        OUT.mkdir(parents=True, exist_ok=True)
        dav1d = large.run([args.dav1d, '--version'], ROOT)
        manifest = dict(source='Original integer-only scenes from generate-large-reference.py; no external imagery',
                        pixel_contract='Frame-major Y/U/V 4:2:0; little-endian uint16; exact native samples',
                        ffmpeg_version=large.run([args.ffmpeg, '-version'], ROOT).stdout.splitlines()[0],
                        dav1d_version=(dav1d.stdout + dav1d.stderr).strip(), libavif_version=lib_version, cases=[])
        for definition in SPECS:
            case = dict(definition)
            name = case['name']
            print(f'Generating {name}...', flush=True)
            (OUT / f'{name}.input.yuv').write_bytes(large.source(case))
            command = [args.ffmpeg, '-y', '-hide_banner', '-f', 'rawvideo', '-pixel_format', f"yuv420p{case['depth']}le",
                       '-video_size', f"{case['width']}x{case['height']}", '-framerate', '25', '-i', f'{name}.input.yuv',
                       '-frames:v', str(case['frames']), '-c:v', 'libaom-av1', '-cpu-used', '6', '-crf', '32',
                       '-b:v', '0', '-threads', '1', '-lag-in-frames', str(case['lag']),
                       '-color_primaries', 'bt709', '-color_trc', 'bt709', '-colorspace', 'bt709', '-color_range', 'tv']
            if case['frames'] == 1:
                command += ['-still-picture', '1']
            command += ['-f', 'obu', f'{name}.obu']
            result = large.run(command, OUT)
            case['encoder_command'] = ['ffmpeg'] + command[1:]
            case['encoder_library_version'] = re.search(r'\[libaom-av1 @ [^\]]+\]\s+(v?\d+\.\d+\.\d+[^\r\n]*)', result.stderr)[1]
            trace, headers = large.mainline.header_trace(args.ffmpeg, OUT / f'{name}.obu', OUT)
            (OUT / f'{name}.trace.txt').write_bytes(trace)
            case['frame_headers'] = headers
            case['sequence_metadata'] = large.sequence_metadata(trace)
            case['evidence'] = evidence(case, headers, large.temporal_units((OUT / f'{name}.obu').read_bytes()))
            command = [args.dav1d, '-q', '--threads=1', '--framedelay=1', '-i', f'{name}.obu', '--muxer=yuv', '-o', f'{name}.reference.yuv']
            large.run(command, OUT)
            case['decoder_command'] = ['dav1d'] + command[1:]
            reference = (OUT / f'{name}.reference.yuv').read_bytes()
            if len(reference) != case['width'] * case['height'] * 3 * case['frames']:
                raise ValueError('Unexpected native reference length')
            if case['frames'] == 1:
                command = [args.ffmpeg, '-y', '-hide_banner', '-i', f'{name}.obu', '-c:v', 'copy', '-f', 'avif', f'{name}.avif']
                large.run(command, OUT)
                case['container_command'] = ['ffmpeg'] + command[1:]
                if large.libavif_native(module, lib, OUT / f'{name}.avif', case) != reference:
                    raise ValueError('Independent AVIF/AV1 pixels differ')
            case['artifacts'] = {p.name: large.sha(p.read_bytes()) for p in sorted(OUT.glob(name + '.*'))}
            manifest['cases'].append(case)
        (OUT / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    else:
        manifest = json.loads((OUT / 'manifest.json').read_text(encoding='utf-8'))
        for case in manifest['cases']:
            name = case['name']
            if large.source(case) != (OUT / f'{name}.input.yuv').read_bytes():
                raise ValueError('Saved scene differs from recipe')
            if large.sequence_metadata((OUT / f'{name}.trace.txt').read_bytes()) != case['sequence_metadata']:
                raise ValueError('Saved metadata differs from trace')
            if evidence(case, case['frame_headers'], large.temporal_units((OUT / f'{name}.obu').read_bytes())) != case['evidence']:
                raise ValueError('Saved presentation evidence differs')
            for filename, digest in case['artifacts'].items():
                if large.sha((OUT / filename).read_bytes()) != digest:
                    raise ValueError(f'Artifact differs: {filename}')
            if args.redecode:
                with tempfile.TemporaryDirectory(prefix='moonav1-stream-') as temporary:
                    large.run([args.dav1d, '-q', '--threads=1', '--framedelay=1', '-i', str(OUT / f'{name}.obu'),
                               '--muxer=yuv', '-o', 'reference.yuv'], temporary)
                    if (Path(temporary) / 'reference.yuv').read_bytes() != (OUT / f'{name}.reference.yuv').read_bytes():
                        raise ValueError('dav1d pixels differ')
                if lib and case['frames'] == 1 and large.libavif_native(module, lib, OUT / f'{name}.avif', case) != (OUT / f'{name}.reference.yuv').read_bytes():
                    raise ValueError('libavif pixels differ')
    content = embedded(manifest['cases'])
    if args.check:
        if EMBED.read_text(encoding='utf-8') != content:
            raise ValueError('Stream embedding is stale')
        print(f"Stream fixtures checked: {len(manifest['cases'])} cases, {sum(c['frames'] for c in manifest['cases'])} frames")
    else:
        EMBED.parent.mkdir(parents=True, exist_ok=True)
        EMBED.write_text(content, encoding='utf-8', newline='\n')
        print(f'Generated {EMBED.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
