#!/usr/bin/env python3
"""Embed existing independent fixtures for public API tests on all backends.

No codec is invoked and no reference artifact is changed. --check only reads
files. Fixture provenance remains in tests/fixtures/*/manifest.json (or the
named companion manifest); this script only serializes those saved samples.
"""

import argparse
import json
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "fixtures"
OUTPUT = ROOT / "native_pixels_test.mbt"
ANIMATION_OUTPUT = ROOT / "native_animation_test.mbt"
EXAMPLE = ROOT / "examples" / "native_pixels" / "fixtures.mbt"


def hex_rows(data):
    return "[\n" + "\n".join(
        f'    "{data[i:i + 56].hex()}",' for i in range(0, len(data), 56)
    ) + "\n  ]"


def input_expr(path):
    return "native_test_bytes(" + hex_rows(path.read_bytes()) + ")"


def samples(path, depth):
    raw = path.read_bytes()
    step = 1 if depth == 8 else 2
    assert len(raw) % step == 0, path
    return [int.from_bytes(raw[i:i + step], "little") for i in range(0, len(raw), step)]


def reference_expr(values):
    # Same lossless RLE packet convention as av1-mainline, always uint16 LE.
    packed = bytearray()
    pos = 0
    while pos < len(values):
        run = 1
        while pos + run < len(values) and values[pos + run] == values[pos] and run < 130:
            run += 1
        if run >= 3:
            packed.append(run + 125)
            packed.extend(values[pos].to_bytes(2, "little"))
            pos += run
        else:
            start = pos
            pos += run
            while pos < len(values) and pos - start < 128:
                if pos + 2 < len(values) and values[pos] == values[pos + 1] == values[pos + 2]:
                    break
                pos += 1
            packed.append(pos - start - 1)
            for value in values[start:pos]:
                packed.extend(value.to_bytes(2, "little"))
    return "native_test_expand(" + hex_rows(packed) + ")"


HELPERS = r'''/// Generated by scripts/generate-native-api-tests.py from existing fixtures.
/// Public API only. Expected native samples come from the original independent
/// dav1d/libavif artifacts; their manifests and provenance remain unchanged.

///|
fn native_test_bytes(rows : Array[String]) -> Array[Byte] {
  let result : Array[Byte] = []
  for row in rows {
    let chars = row.to_array()
    for i in 0..<(chars.length() / 2) {
      let hi = chars[i * 2].to_int()
      let lo = chars[i * 2 + 1].to_int()
      result.push((((if hi >= 97 { hi - 87 } else { hi - 48 }) << 4) |
        (if lo >= 97 { lo - 87 } else { lo - 48 })).to_byte())
    }
  }
  result
}

///|
fn native_test_expand(rows : Array[String]) -> Array[Int] {
  let bytes = native_test_bytes(rows)
  let result : Array[Int] = []
  let mut pos = 0
  while pos < bytes.length() {
    let control = bytes[pos].to_int()
    pos = pos + 1
    if control < 128 {
      for _ in 0..<(control + 1) {
        result.push(bytes[pos].to_int() | (bytes[pos + 1].to_int() << 8))
        pos = pos + 2
      }
    } else {
      let value = bytes[pos].to_int() | (bytes[pos + 1].to_int() << 8)
      pos = pos + 2
      for _ in 0..<(control - 125) { result.push(value) }
    }
  }
  result
}

///|
fn native_test_frame(
  frame : Av1NativeFrame,
  reference : Array[Int],
  start : Int,
  width : Int,
  height : Int,
  depth : Int,
  sx : Bool,
  sy : Bool,
  mono? : Bool = false,
) -> Int raise {
  assert_eq((frame.width, frame.height, frame.bit_depth), (width, height, depth))
  assert_eq(frame.planes.length(), if mono { 1 } else { 3 })
  if !mono {
    assert_eq((frame.subsampling_x, frame.subsampling_y), (sx, sy))
  }
  let mut offset = start
  for p in 0..<frame.planes.length() {
    let plane = frame.planes[p]
    let w = if p > 0 && sx { (width + 1) / 2 } else { width }
    let h = if p > 0 && sy { (height + 1) / 2 } else { height }
    assert_eq((plane.width, plane.height), (w, h))
    assert_eq(plane.data.length(), w * h)
    for value in plane.data {
      assert_true(value >= 0 && value < (1 << depth))
      assert_eq(value, reference[offset])
      offset = offset + 1
    }
  }
  offset
}
'''


def raw_case(directory, name, width, height, depth, sx=True, sy=True, mono=False):
    folder = FIXTURES / directory
    args = f"{width}, {height}, {depth}, {str(sx).lower()}, {str(sy).lower()}, mono={str(mono).lower()}"
    result = f'''///|
// Reference: tests/fixtures/{directory}/{name}.reference.yuv
test "native API raw {name}" {{
  let input = {input_expr(folder / (name + '.obu'))}
  let expected = {reference_expr(samples(folder / (name + '.reference.yuv'), depth))}
  let frame = av1_decode_native(input).unwrap()
  assert_eq(native_test_frame(frame, expected, 0, {args}), expected.length())
  let first = frame.planes[0].data[0]
  input[0] = 0xff
  assert_eq(frame.planes[0].data[0], first)
}}
'''
    if mono:
        result = result.replace('  let first =', '''  assert_true(av1_video_decode_temporal_unit_native(av1_video_decoder(), input) is None)
  let video = av1_video_decode_temporal_unit_native(av1_video_decoder(), input, allow_monochrome=true).unwrap()
  assert_eq(video.length(), 1)
  assert_eq(native_test_frame(video[0], expected, 0, ''' + args + '''), expected.length())
  let first =''')
    return result


def video_case(directory, name, depth, width=64, height=64, sx=True, sy=True, count=4, suffix='reference.yuv'):
    folder = FIXTURES / directory
    return f'''///|
// Reference: tests/fixtures/{directory}/{name}.{suffix}
test "native API video {name}" {{
  let input = {input_expr(folder / (name + '.obu'))}
  let expected = {reference_expr(samples(folder / (name + '.' + suffix), depth))}
  let frames = av1_video_decode_temporal_unit_native(av1_video_decoder(), input).unwrap()
  assert_eq(frames.length(), {count})
  let mut offset = 0
  for frame in frames {{
    offset = native_test_frame(frame, expected, offset, {width}, {height}, {depth}, {str(sx).lower()}, {str(sy).lower()})
  }}
  assert_eq(offset, expected.length())
}}
'''


def avif_case(directory, name, width, height, depth, sx, sy, color_file,
              alpha_file=None, prem=False, mono=False, full=True, color_ids=None,
              reference_depth=None):
    folder = FIXTURES / directory
    native_depth = depth if reference_depth is None else reference_depth
    body = f'''///|
// References: tests/fixtures/{directory}/{color_file}'''
    if alpha_file:
        body += f" and {alpha_file}"
    body += f'''
test "native API AVIF {name}" {{
  let input = {input_expr(folder / (name + '.avif'))}
  let expected = {reference_expr(samples(folder / color_file, native_depth))}
  let image = avif_decode_native(input).unwrap()
  assert_eq(native_test_frame(image.color, expected, 0, {width}, {height}, {depth}, {str(sx).lower()}, {str(sy).lower()}, mono={str(mono).lower()}), expected.length())
  assert_eq(image.color.full_range, {str(full).lower()})
  assert_eq(image.premultiplied, {str(prem).lower()})
'''
    if color_ids:
        body += f'''  assert_eq((image.color.color_primaries, image.color.transfer_characteristics, image.color.matrix_coefficients), {color_ids})
'''
    if alpha_file:
        body += f'''  let alpha_expected = {reference_expr(samples(folder / alpha_file, depth))}
  let alpha = image.alpha.unwrap()
  assert_eq(native_test_frame(alpha, alpha_expected, 0, {width}, {height}, {depth}, false, false, mono=true), alpha_expected.length())
  let original = image.color.planes[0].data[0]
  alpha.planes[0].data[0] = -1
  assert_eq(image.color.planes[0].data[0], original)
  // A corrupt auxiliary payload must reject the whole native/RGBA image.
  let descriptor = avif_alpha_item_descriptor(input).unwrap()
  input[descriptor.extents[0].offset] = 0xff
  assert_true(avif_decode_native(input) is None)
  assert_true(avif_decode_rgba(input) is None)
'''
    else:
        body += "  assert_true(image.alpha is None)\n"
    return body + "}\n"


def state_case():
    folder = FIXTURES / "av1-obu-assembly"
    data = (folder / "hidden_inter_show_existing.obu").read_bytes()
    # These boundaries are recorded by this existing fixture's OBU structure.
    assert data[121:123] == data[172:174] == b'\x12\x00'
    assert data[169:172] == b'\x1a\x01\x98'
    ref = samples(folder / "hidden_inter_show_existing.reference.yuv", 8)
    return f'''///|
// Existing hidden_inter_show_existing fixture, split at its OBU boundaries.
test "native API ownership hidden updates show-existing and mixed outputs" {{
  let key = native_test_bytes({hex_rows(data[:121])})
  let hidden = native_test_bytes({hex_rows(data[121:169])})
  let show = native_test_bytes({hex_rows(data[169:172])})
  let inter = native_test_bytes({hex_rows(data[172:])})
  let expected = {reference_expr(ref)}
  let decoder = av1_video_decoder()
  let first = av1_video_decode_temporal_unit_native(decoder, key).unwrap()[0]
  let next = native_test_frame(first, expected, 0, 64, 64, 8, true, true)
  for plane in first.planes {{
    for i in 0..<plane.data.length() {{ plane.data[i] = 0 }}
  }}
  assert_eq(av1_video_decode_temporal_unit_native(decoder, hidden).unwrap().length(), 0)
  let shown = av1_video_decode_temporal_unit_native(decoder, show).unwrap()[0]
  let end = native_test_frame(shown, expected, next, 64, 64, 8, true, true)
  for plane in shown.planes {{
    for i in 0..<plane.data.length() {{ plane.data[i] = 0 }}
  }}
  let again = av1_video_decode_temporal_unit_native(decoder, show).unwrap()[0]
  assert_eq(native_test_frame(again, expected, next, 64, 64, 8, true, true), end)
  let rgb = av1_video_decode_temporal_unit(decoder, inter).unwrap()[0]
  let fresh = av1_video_decoder()
  av1_video_decode_temporal_unit(fresh, key) |> ignore
  let expected_rgb = av1_video_decode_temporal_unit(fresh, inter).unwrap()[0]
  for i in 0..<rgb.data.length() {{ assert_eq(rgb.data[i], expected_rgb.data[i]) }}
  assert_eq(native_test_frame(again, expected, next, 64, 64, 8, true, true), end)
}}

///|
test "native API rejects malformed input and distinguishes no presentation" {{
  assert_true(av1_decode_native([]) is None)
  assert_true(avif_decode_native([]) is None)
  assert_true(av1_decode_native([0x0a, 0x01, 0x18]) is None)
  assert_true(av1_video_decode_temporal_unit_native(av1_video_decoder(), [0x1a, 0x01, 0x98]) is None)
  let sequence = native_test_bytes({hex_rows(data[:13])})
  assert_true(av1_decode_native(sequence) is None)
  assert_eq(av1_video_decode_temporal_unit_native(av1_video_decoder(), sequence).unwrap().length(), 0)
}}
'''


def generate():
    result = [HELPERS]
    for depth in (8, 10, 12):
        result.append(raw_case("av1-highbd-ac", f"mixed_yuv_{depth}bit_q30", 64, 64, depth))
    result.append(raw_case("av1-monochrome", "mono_64x64_1tile_12bit_q30", 64, 64, 12, mono=True))
    manifest = json.loads((FIXTURES / 'av1-palette/constructed-manifest.json').read_text())
    odd = next(f for f in manifest['fixtures'] if f['name'] == 'constructed_size4_color12_odd_padding')
    result.append(raw_case("av1-palette", odd['name'], *odd['dimensions'], 12))
    for depth, sampling in ((8, '420'), (10, '420'), (12, '420'), (10, '422'), (10, '444')):
        result.append(video_case('av1-mainline', f'combined_{depth}bit_{sampling}_64x64', depth,
                                 sx=sampling != '444', sy=sampling == '420'))
    result.append(video_case('av1-film-grain', 'sequence_inherit_12bit', 12, suffix='display.yuv'))
    result.append(video_case('av1-obu-assembly', 'spatial_layer_presentation', 8, count=3))
    for depth, sampling, width in ((10, '422', 98), (12, '444', 99)):
        name = f'nclx709_{sampling}_{depth}bit_2x2_odd_crop'
        result.append(avif_case('avif-grid-sampling-color', name, width, 97, depth,
                                sampling != '444', False, name + '.native.bin',
                                color_ids='(1, 13, 1)', reference_depth=12))
    for depth, matrix in ((10, 8), (12, 0)):
        name = f'static_matrix{matrix}_{depth}bit'
        result.append(avif_case('avif-premultiplied-alpha', name, 16, 16, depth, False, False,
                                name + '_frame0.yuv.bin', name + '_frame0.alpha.bin', prem=True))
    name = 'static_matrix6_8bit_reversed_prem'
    result.append(avif_case('avif-premultiplied-alpha', name, 16, 16, 8, False, False,
                            name + '_frame0.yuv.bin', name + '_frame0.alpha.bin'))
    name = 'alpha_grid_grid_12bit'
    result.append(avif_case('avif-grid', name, 96, 98, 12, True, True,
                            name + '.color.yuv', name + '.alpha.yuv', full=False))
    name = 'nclx709_limited_444_10bit'
    result.append(avif_case('av1-color', name, 16, 16, 10, False, False,
                            name + '.yuv', full=False, color_ids='(1, 1, 1)'))
    result.append(state_case())
    raw = '\n'.join(result)
    return subprocess.run(['moonfmt', '-'], input=raw, text=True, encoding='utf-8',
                          capture_output=True, check=True).stdout


ANIMATION_HELPERS = '''/// Generated by scripts/generate-native-api-tests.py from existing fixtures.
/// Native color/alpha references in avif-premultiplied-alpha come from libavif.
/// avif-animation-alpha retains independent native alpha and RGBA, not native
/// color; those cases check exact alpha, timing, metadata and rejection.

///|
fn native_animation_timing(animation : AvifNativeAnimation) -> Unit raise {
  assert_eq(animation.timescale, 1000)
  assert_eq(animation.frames.length(), 3)
  for i in 0..<3 {
    let frame = animation.frames[i]
    assert_eq(frame.index, i)
    assert_eq(frame.timestamp, [0, 100, 300][i])
    assert_eq(frame.duration, [100, 200, 300][i])
    assert_eq(frame.timescale, 1000)
  }
  for entry in [(0, 0), (99, 0), (100, 1), (299, 1),
                       (300, 2), (599, 2), (600, 0), (700, 1),
                       (900, 2), (1200, 0), (2147483647, 1)] {
    let (time, index) = entry
    assert_eq(animation.frame_at(time).unwrap().index, index)
  }
  assert_true(animation.frame_at(-1) is None)
}

///|
fn native_animation_ownership(animation : AvifNativeAnimation) -> Unit raise {
  let next_color = animation.frames[1].image.color.planes[0].data[0]
  let selected = animation.frame_at(0).unwrap()
  selected.image.color.planes[0].data[0] = -1
  // Selection borrows the stored frame, but distinct decoded frames own data.
  assert_eq(animation.frames[0].image.color.planes[0].data[0], -1)
  assert_eq(animation.frames[1].image.color.planes[0].data[0], next_color)
  if selected.image.alpha is Some(alpha) {
    let next_alpha = animation.frames[1].image.alpha.unwrap().planes[0].data[0]
    alpha.planes[0].data[0] = -1
    assert_eq(animation.frames[1].image.alpha.unwrap().planes[0].data[0], next_alpha)
  }
  // A caller can replace entries in the public FixedArray. Refuse a broken
  // timeline before selecting even an otherwise-valid earlier frame.
  animation.frames[2] = animation.frames[1]
  assert_true(animation.frame_at(0) is None)
}
'''


def animation_prem_case(folder, case):
    name = case['name']
    depth = case['depth']
    colors = [samples(folder / f"{case['reference']}_frame{i}.yuv.bin", depth) for i in range(3)]
    alphas = [samples(folder / f"{case['reference']}_frame{i}.alpha.bin", depth) for i in range(3)]
    color_expr = ',\n'.join(reference_expr(frame) for frame in colors)
    alpha_expr = ',\n'.join(reference_expr(frame) for frame in alphas)
    return f'''///|
// Native references: tests/fixtures/avif-premultiplied-alpha/{case['reference']}_frame*.{{yuv,alpha}}.bin
test "native animation {name}" {{
  let input = {input_expr(folder / case['file'])}
  let animation = avif_decode_animation_native(input).unwrap()
  native_animation_timing(animation)
  let colors = [{color_expr}]
  let alphas = [{alpha_expr}]
  for i in 0..<3 {{
    let image = animation.frames[i].image
    assert_eq(native_test_frame(image.color, colors[i], 0, 16, 16, {depth}, false, false), colors[i].length())
    assert_eq(image.color.matrix_coefficients, {case['matrix']})
    assert_true(image.color.full_range)
    assert_eq(image.premultiplied, {str(case['premultiplied']).lower()})
    let alpha = image.alpha.unwrap()
    assert_eq(native_test_frame(alpha, alphas[i], 0, 16, 16, {depth}, false, false, mono=true), alphas[i].length())
    assert_true(alpha.full_range)
  }}
  native_animation_ownership(animation)
}}
'''


def animation_alpha_case(folder, case):
    name, depth = case['name'], case['depth']
    result = f'''///|
// Existing avif-animation-alpha manifest case: {name}.
test "native animation {name}" {{
  let input = {input_expr(folder / case['file'])}
'''
    if case['result'] == 'reject':
        return result + '''  assert_true(avif_decode_animation_native(input) is None)
}
'''
    result += '''  let animation = avif_decode_animation_native(input).unwrap()
  native_animation_timing(animation)
'''
    if case['result'] == 'opaque':
        result += '''  for frame in animation.frames {
    assert_true(frame.image.alpha is None)
    assert_false(frame.image.premultiplied)
    assert_eq((frame.image.color.width, frame.image.color.height, frame.image.color.bit_depth), (16, 16, 8))
    assert_eq(frame.image.color.planes.length(), 1)
  }
'''
    else:
        prefix = case.get('rgba_prefix', f'alpha_sequence_{depth}bit')
        references = [samples(folder / f'{prefix}_frame{i}.alpha.bin', depth) for i in range(3)]
        alpha_expr = ',\n'.join(reference_expr(frame) for frame in references)
        mono = not name.startswith('nclx')
        result += f'''  let expected = [{alpha_expr}]
  for i in 0..<3 {{
    let image = animation.frames[i].image
    let color = image.color
    assert_eq((color.width, color.height, color.bit_depth), (16, 16, {depth}))
    assert_eq(color.planes.length(), {1 if mono else 3})
    assert_false(image.premultiplied)
    let alpha = image.alpha.unwrap()
    assert_eq(native_test_frame(alpha, expected[i], 0, 16, 16, {depth}, false, false, mono=true), expected[i].length())
    assert_true(alpha.full_range)
'''
        if not mono:
            result += '    assert_eq((color.color_primaries, color.transfer_characteristics, color.matrix_coefficients), (1, 13, 1))\n'
        result += '  }\n'
    result += '''  native_animation_ownership(animation)
}
'''
    return result


def generate_animation():
    result = [ANIMATION_HELPERS]
    prem_folder = FIXTURES / 'avif-premultiplied-alpha'
    prem = json.loads((prem_folder / 'manifest.json').read_text(encoding='utf8'))
    for case in prem['cases']:
        if case['animated']:
            result.append(animation_prem_case(prem_folder, case))
    alpha_folder = FIXTURES / 'avif-animation-alpha'
    alpha = json.loads((alpha_folder / 'manifest.json').read_text(encoding='utf8'))
    for case in alpha['fixtures']:
        result.append(animation_alpha_case(alpha_folder, case))
    result.append(f'''///|
test "native animation rejects a corrupt later sample without partial output" {{
  let input = {input_expr(prem_folder / 'animation_matrix0_12bit.avif')}
  let descriptor = avif_animation_descriptor(input).unwrap()
  assert_eq(descriptor.frames.length(), 3)
  let valid = avif_decode_animation_native(input).unwrap()
  let original = valid.frames[0].image.color.planes[0].data[0]
  input[descriptor.frames[2].offset] = 0xff
  assert_true(avif_decode_animation_native(input) is None)
  assert_true(avif_decode_animation(input) is None)
  assert_eq(valid.frames[0].image.color.planes[0].data[0], original)
  assert_true(avif_decode_animation_native([]) is None)
  assert_true(avif_decode_animation_native([0x00, 0x00, 0x00]) is None)
}}
''')
    return subprocess.run(['moonfmt', '-'], input='\n'.join(result), text=True,
                          encoding='utf-8', capture_output=True, check=True).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    example = '/// Generated by scripts/generate-native-api-tests.py.\n'
    for var, path in [('example_obu', 'av1-highbd-ac/y_cosine_12bit_q30.obu'),
                      ('example_avif', 'avif-premultiplied-alpha/static_matrix8_10bit.avif'),
                      ('example_animation', 'avif-premultiplied-alpha/animation_matrix0_12bit.avif')]:
        data = (FIXTURES / path).read_bytes()
        example += f'\n///|\n/// Unchanged tests/fixtures/{path}.\nlet {var} : Array[Byte] = [\n'
        example += '\n'.join('  ' + ', '.join(f'0x{x:02x}' for x in data[i:i+12]) + ','
                             for i in range(0, len(data), 12))
        example += '\n]\n'
    example = subprocess.run(['moonfmt', '-'], input=example, text=True, encoding='utf-8',
                             capture_output=True, check=True).stdout
    for path, text in [(OUTPUT, generate()), (ANIMATION_OUTPUT, generate_animation()), (EXAMPLE, example)]:
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                raise SystemExit(f'{path.name} differs; regenerate from the existing fixtures')
            print(f'{path.name}: matches existing independent fixtures')
        else:
            path.write_text(text, encoding='utf-8', newline='\n')
            print(f'Wrote {path.name}')


if __name__ == '__main__':
    main()
